<a href="https://colab.research.google.com/github/RayaheenMseri/EcoNest/blob/main/notebooks/Detection_of_AI_Generated_Arabic_Text_Phase_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
!pip install -q datasets

In [21]:
# Import data preparation functions
import data_preparation as dp

In [22]:
# Load the dataset
dataset_name = "KFUPM-JRCAI/arabic-generated-abstracts"

dataset = dp.load_data(dataset_name)

print(dataset)

DatasetDict({
    by_polishing: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2851
    })
    from_title: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2963
    })
    from_title_and_content: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2574
    })
})

In [23]:
# Inspect the structure of each subset
for split in dataset:

    print(f"\n\033[1mSubset: {split}\033[0m")

    dp.inspect_structure(dataset[split])

Subset: by_polishing
Rows: 2851
Columns: 5
Features: {'original_abstract': Value('string'), 'allam_generated_abstract': Value('string'), 'jais_generated_abstract': Value('string'), 'llama_generated_abstract': Value('string'), 'openai_generated_abstract': Value('string')}

Subset: from_title
Rows: 2963
Columns: 5
Features: {'original_abstract': Value('string'), 'allam_generated_abstract': Value('string'), 'jais_generated_abstract': Value('string'), 'llama_generated_abstract': Value('string'), 'openai_generated_abstract': Value('string')}

Subset: from_title_and_content
Rows: 2574
Columns: 5
Features: {'original_abstract': Value('string'), 'allam_generated_abstract': Value('string'), 'jais_generated_abstract': Value('string'), 'llama_generated_abstract': Value('string'), 'openai_generated_abstract': Value('string')}

In [24]:
# Convert each subset to a pandas DataFrame
subset = {}

for split in dataset:
    subset[split] = dp.to_dataframe(dataset[split])

print("Subset:", list(subset.keys()))

Subset: ['by_polishing', 'from_title', 'from_title_and_content']

In [25]:
# Define the original and comparison columns
original_column = "original_abstract"

generated_columns = [
    "allam_generated_abstract",
    "jais_generated_abstract",
    "llama_generated_abstract",
    "openai_generated_abstract"
]

In [26]:
# Check the data types of each subset
for split, data in subset.items():

    print(f"\n\033[1mSubset: {split}\033[0m")

    dp.check_data_types(data)

Subset: by_polishing
original_abstract            object
allam_generated_abstract     object
jais_generated_abstract      object
llama_generated_abstract     object
openai_generated_abstract    object
dtype: object

Subset: from_title
original_abstract            object
allam_generated_abstract     object
jais_generated_abstract      object
llama_generated_abstract     object
openai_generated_abstract    object
dtype: object

Subset: from_title_and_content
original_abstract            object
allam_generated_abstract     object
jais_generated_abstract      object
llama_generated_abstract     object
openai_generated_abstract    object
dtype: object

In [27]:
# Display the first 5 rows of each subset
for split, data in subset.items():

    print(f"\n\033[1mSubset: {split}\033[0m")

    display(dp.preview_data(data))

Subset: by_polishing

,original_abstract,allam_generated_abstract,jais_generated_abstract,llama_generated_abstract,openai_generated_abstract
0,كثيرا ما ارتبطت المصادر التاريخية في الأندلس خ...,يتناول هذا البحث موضوع التعليم بين النساء الأن...,تدرس هذه الدراسة دور المرأة في التعليم في الأن...,يُقدم هذا البحث دراسة شاملة حول حالة التعليم ع...,صور نظام التعليم عند المرأة الأندلسية تستند إل...
1,يعد العامل الثقافي احد ابرز الاسباب التي يعزى ...,يتناول هذا البحث دراسة انهيار دولة الموحدين من...,كان العامل الثقافي من بين الأسباب الرئيسية الت...,يعد العامل الثقافي أحد أبرز الأسباب التي يعزى ...,انهيار دولة الموحدين يعود بشكل كبير للعوامل ال...
2,شكلت تلك الجهود والمساعي الرائدة التي قام بها ...,هدفت هذه الدراسة إلى تسليط الضوء على جهود قادة...,تدرس هذه الدراسة جهود قادة الثورة الجزائرية خل...,شكلت الجهود التي بذلها قادة الثورة الجزائرية خ...,جهود قادة الثورة الجزائرية خلال المرحلة الأولى...
3,يقوم المقال على اشكالية الضرائب الغير شرعية في...,يتناول هذا البحث إشكالية الضرائب غير الشرعية ف...,تدرس المقالة مشكلة الضرائب غير الشرعية في مراح...,يقوم البحث على دراسة الضرائب غير الشرعية في دو...,المقال يناقش قضية الضرائب غير الشرعية في دولتي...
4,تتفق المصادر التاريخية المتوفرة حول موضوع تطور...,تتناول هذه الدراسة حركة الانتصار للحريات الديم...,حركة انتصار الحريات الديمقراطية (MTLD)، وهي حر...,تُظهر المصادر التاريخية المتاحة حول تطور الحرك...,حركة انتصار الحريات الديمقراطية (MTLD) في الجز...

Subset: from_title

,original_abstract,allam_generated_abstract,jais_generated_abstract,llama_generated_abstract,openai_generated_abstract
0,كثيرا ما ارتبطت المصادر التاريخية في الأندلس خ...,يهدف هذا البحث إلى دراسة نظام التعليم عند المر...,تدرس هذه الورقة البحثية نظام التعليم لدى المرأ...,تهدف هذه الورقة البحثية إلى استكشاف صور نظام ا...,البحث يستكشف نظام التعليم عند المرأة الأندلسية...
1,يعد العامل الثقافي احد ابرز الاسباب التي يعزى ...,تهدف هذه الدراسة إلى تحليل انهيار دولة الموحدي...,تدرس هذه الورقة البحثية انهيار دولة الموحدين، ...,يتناول هذا البحث انهيار دولة الموحدين من خلال ...,تتناول هذه الدراسة البحثية انهيار دولة الموحدي...
2,يقوم المقال على اشكالية الضرائب الغير شرعية في...,تهدف هذه الدراسة إلى استكشاف ظاهرة الضرائب غير...,تدرس هذه الورقة البحثية ظاهرة التهرب الضريبي ف...,يُقدم هذا البحث دراسة تحليلية شاملة للضرائب غي...,تتناول هذه الدراسة البحثية موضوع الضرائب غير ا...
3,تتفق المصادر التاريخية المتوفرة حول موضوع تطور...,تهدف هذه الدراسة إلى تحليل حركة انتصار الحريات...,حركة انتصار الحريات الديمقراطية -MTLD-(1945-19...,حركة انتصار الحريات الديمقراطية (MTLD) بين الأ...,"دراسـة ""حركـة انتصـار الحريّـات الديمقراطيـة -..."
4,تعددت صور الحياة الثقافية و الفكرية و الأدبية ...,تهدف هذه الدراسة إلى استكشاف تأثير السلطة العل...,تدرس هذه الورقة البحثية تأثير السلطة العالمة ع...,يستعرض هذا البحث تأثير السلطة العالمة على الإب...,تتناول هذه الورقة البحثية تأثير الهيمنة العالم...

Subset: from_title_and_content

,original_abstract,allam_generated_abstract,jais_generated_abstract,llama_generated_abstract,openai_generated_abstract
0,كثيرا ما ارتبطت المصادر التاريخية في الأندلس خ...,يتناول هذا البحث موضوع نظام التعليم عند المرأة...,تتناول هذه الدراسة نظام التعليم عند المرأة الأ...,تناولت هذه الدراسة نظام التعليم عند المرأة الأ...,يركز البحث على نظام التعليم للمرأة في الأندلس،...
1,يعد العامل الثقافي احد ابرز الاسباب التي يعزى ...,يتناول هذا البحث دراسة خلفيات انهيار دولة المو...,يعد العامل الثقافي أحد أبرز الأسباب التي أدت إ...,انهيار دولة الموحدين – دراسة في الخلفيات الثقا...,تناول البحث انهيار دولة الموحدين من منظور خلفي...
2,شكلت تلك الجهود والمساعي الرائدة التي قام بها ...,يتناول هذا البحث موضوع تسليح جيش التحرير الوطن...,للأسف، النص المقدم غير واضح وغير قابل للقراءة ...,تسليح جيش التحرير الوطني عبر الحدود الغربية خل...,يبحث هذا البحث في تسليح جيش التحرير الوطني الج...
3,يقوم المقال على اشكالية الضرائب الغير شرعية في...,يتناول هذا البحث موضوع الضرائب غير الشرعية في ...,يناقش المقال مشكلة الضرائب غير الشرعية في مراح...,تناولت هذه الدراسة الضرائب غير الشرعية في دولت...,يتناول البحث مسألة الضرائب غير الشرعية في دولت...
4,تعددت صور الحياة الثقافية و الفكرية و الأدبية ...,يتناول هذا البحث تأثير السلطة العالمة في الإبد...,تتناول هذه الدراسة تأثير السلطة العالمة على ال...,أثر السلطة العالمة في الإبداع الفكري والأدبي ا...,يتناول البحث موضوع دور السلطة العالمة في تعزيز...

In [28]:
# Check whether the label column exists
for split, data in subset.items():

    print(f"\n\033[1mSubset: {split}\033[0m")

    result = dp.check_column(data, "label")

    if result is None:
        print("No label column found")
    else:
        print(result)

Subset: by_polishing
No label column found

Subset: from_title
No label column found

Subset: from_title_and_content
No label column found

In [29]:
# Check the distribution of human and AI-generated texts
for split, data in subset.items():

    human_texts, ai_texts = dp.count_class_distribution(
        data,
        original_column,
        generated_columns
    )

    print(f"\n\033[1mSubset: {split}\033[0m")
    print("Human:", human_texts)
    print("AI-generated:", ai_texts)

Subset: by_polishing
Human: 2851
AI-generated: 11404

Subset: from_title
Human: 2963
AI-generated: 11852

Subset: from_title_and_content
Human: 2574
AI-generated: 10296

In [30]:
# Check for empty or whitespace-only cells
for split, data in subset.items():

    print(f"\n\033[1mSubset: {split}\033[0m")

    empty_values = dp.check_empty_values(data)

    for column, count in empty_values.items():
        print(f"{column}: {count} empty values")

Subset: by_polishing
original_abstract: 0 empty values
allam_generated_abstract: 0 empty values
jais_generated_abstract: 0 empty values
llama_generated_abstract: 0 empty values
openai_generated_abstract: 0 empty values

Subset: from_title
original_abstract: 0 empty values
allam_generated_abstract: 0 empty values
jais_generated_abstract: 0 empty values
llama_generated_abstract: 0 empty values
openai_generated_abstract: 0 empty values

Subset: from_title_and_content
original_abstract: 0 empty values
allam_generated_abstract: 0 empty values
jais_generated_abstract: 0 empty values
llama_generated_abstract: 0 empty values
openai_generated_abstract: 0 empty values

In [31]:
# Check for missing values
for split, data in subset.items():

    print(f"\n\033[1mSubset: {split}\033[0m")

    print(dp.check_missing_values(data))

Subset: by_polishing
original_abstract            0
allam_generated_abstract     0
jais_generated_abstract      0
llama_generated_abstract     0
openai_generated_abstract    0
dtype: int64

Subset: from_title
original_abstract            0
allam_generated_abstract     0
jais_generated_abstract      0
llama_generated_abstract     0
openai_generated_abstract    0
dtype: int64

Subset: from_title_and_content
original_abstract            0
allam_generated_abstract     0
jais_generated_abstract      0
llama_generated_abstract     0
openai_generated_abstract    0
dtype: int64

In [32]:
# Check for duplicate rows
for split, data in subset.items():

    print(f"\n\033[1mSubset: {split}\033[0m")

    duplicates = dp.check_duplicates(data)

    print("Duplicates:", duplicates)

Subset: by_polishing
Duplicates: 0

Subset: from_title
Duplicates: 0

Subset: from_title_and_content
Duplicates: 0

In [33]:
# Check the number of unique values in each column
for split, data in subset.items():

    print(f"\n\033[1mSubset: {split}\033[0m")

    unique_values = dp.check_unique_values(data)

    for column, count in unique_values.items():
        print(f"{column}: {count} unique values")

Subset: by_polishing
original_abstract: 2851 unique values
allam_generated_abstract: 2851 unique values
jais_generated_abstract: 2851 unique values
llama_generated_abstract: 2851 unique values
openai_generated_abstract: 2851 unique values

Subset: from_title
original_abstract: 2963 unique values
allam_generated_abstract: 2963 unique values
jais_generated_abstract: 2963 unique values
llama_generated_abstract: 2963 unique values
openai_generated_abstract: 2963 unique values

Subset: from_title_and_content
original_abstract: 2574 unique values
allam_generated_abstract: 2574 unique values
jais_generated_abstract: 2571 unique values
llama_generated_abstract: 2574 unique values
openai_generated_abstract: 2574 unique values

In [34]:
# Check exact matches between the original and generated columns
for split, data in subset.items():

    print(f"\n\033[1mSubset: {split}\033[0m")

    exact_matches = dp.check_exact_matches(
        data,
        original_column,
        generated_columns
    )

    for column, count in exact_matches.items():
        print(f"{column}: {count} exact matches")

Subset: by_polishing
allam_generated_abstract: 0 exact matches
jais_generated_abstract: 2 exact matches
llama_generated_abstract: 14 exact matches
openai_generated_abstract: 0 exact matches

Subset: from_title
allam_generated_abstract: 0 exact matches
jais_generated_abstract: 0 exact matches
llama_generated_abstract: 0 exact matches
openai_generated_abstract: 0 exact matches

Subset: from_title_and_content
allam_generated_abstract: 0 exact matches
jais_generated_abstract: 0 exact matches
llama_generated_abstract: 0 exact matches
openai_generated_abstract: 0 exact matches

In [35]:
# Check for additional numbers in the by_polishing subset
data = subset["by_polishing"]

print(f"\n\033[1mSubset: by_polishing\033[0m")

additional_numbers = dp.check_additional_numbers(
    data,
    original_column,
    generated_columns
)

for column, count in additional_numbers.items():
    print(f"{column}: {count} texts with additional numbers")

Subset: by_polishing
allam_generated_abstract: 146 texts with additional numbers
jais_generated_abstract: 86 texts with additional numbers
llama_generated_abstract: 105 texts with additional numbers
openai_generated_abstract: 136 texts with additional numbers